#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  hang1,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  hang2,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  cat1,           sensorDigitalOut)
#pragma config(Sensor, dgtl4,  cat2,           sensorDigitalOut)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIEM,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftfrontdrive, tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftmiddledrive, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftreardrive, tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           leftlift,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftintake,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           rightintake,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           rightlift,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           rightreardrive, tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000))
#pragma config(Motor,  port9,           rightmiddledrive, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightfrontdrive, tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
//Variable that will carry between modes

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//LCD Display code.
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
//Declare count variable to keep track of our choice
	int count = 0;
	string mainBattery;
//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

void DriveForward(int speed, int time)
{
	motor[leftmiddledrive] = (speed)*(((4000-(pot))/4000));
	motor[rightmiddledrive] = (speed)*(((4000-(pot))/4000));
	motor[rightfrontdrive] = (speed)*(((4000-(pot))/4000));
	motor[leftfrontdrive] = (speed)*(((4000-(pot))/4000));
	motor[rightreardrive] = (speed)*(((4000-(pot))/4000));
	motor[leftreardrive] = (speed)*(((4000-(pot))/4000));
	wait1Msec(time);
}

//

/////////////////////////////////////////////////7////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{


	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
		bLCDBacklight = true;
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Red Middle");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "blue Middle");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "RED hang");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Blue hang");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:

			count = 0;

			break;

		}
	}

}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
 	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Red Middle");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(250);// Robot waits for 250 milliseconds
	    motor[leftintake]=-127;
	    motor[rightintake]=-127;
	wait1Msec(100);
	    motor[leftintake]=127;
	    motor[rightintake]=127;
	wait1Msec(100);
	    motor[leftintake]=-127;
	    motor[rightintake]=-127;
	wait1Msec(100);
	    motor[leftlift]=10;
	    motor[rightlift]=10;
        motor[leftfrontdrive]=127;
	    motor[rightfrontdrive]=127;
	    motor[leftmiddledrive]=127;
	    motor[rightmiddledrive]=127;
	    motor[leftreardrive]=127;
	    motor[rightreardrive]=127;
	wait1Msec(2250);
	    motor[rightlift]=40;
	    motor[leftlift]=40;
        motor[leftfrontdrive]=127;
	    motor[rightfrontdrive]=-127;
	    motor[leftmiddledrive]=127;
	    motor[rightmiddledrive]=-127;
	    motor[leftreardrive]=127;
	    motor[rightreardrive]=-127;
	wait1Msec(533);
        motor[leftfrontdrive]=127;
	    motor[rightfrontdrive]=127;
	    motor[leftmiddledrive]=127;
	    motor[rightmiddledrive]=127;
	    motor[leftreardrive]=127;
	    motor[rightreardrive]=127;
	    motor[rightlift]=10;
	    motor[leftlift]=10;
	wait1Msec(400);
        motor[leftfrontdrive]=0;
	    motor[rightfrontdrive]=0;
	    motor[leftmiddledrive]=0;
	    motor[rightmiddledrive]=0;
	    motor[leftreardrive]=0;
	    motor[rightreardrive]=0;
	wait1Msec(200);
        motor[leftfrontdrive]=-127;
	    motor[rightfrontdrive]=-127;
	    motor[leftmiddledrive]=-127;
	    motor[rightmiddledrive]=-127;
	    motor[leftreardrive]=-127;
	    motor[rightreardrive]=-127;
  wait1Msec(400);
        motor[leftfrontdrive]=-127;
	    motor[rightfrontdrive]=127;
	    motor[leftmiddledrive]=-127;
	    motor[rightmiddledrive]=127;
	    motor[leftreardrive]=-127;
	    motor[rightreardrive]=127;
	wait1Msec(550);
        motor[leftfrontdrive]=-127;
	    motor[rightfrontdrive]=-127;
	    motor[leftmiddledrive]=-127;
	    motor[rightmiddledrive]=-127;
	    motor[leftreardrive]=-127;
	    motor[rightreardrive]=-127;
            motor[rightlift]=-10;
            motor[leftlift]=-10;
	wait1Msec(2050);
        motor[leftfrontdrive]=0;
	    motor[rightfrontdrive]=0;
	    motor[leftmiddledrive]=0;
	    motor[rightmiddledrive]=0;
	    motor[leftreardrive]=0;
	    motor[rightreardrive]=0;
	wait1Msec(2000);
  if(SensorValue(pot) <1400)
  {
			if(SensorValue(pot) < 1250){
				motor[leftlift] = 127;
				motor[rightlift] = 127;
			}
			else if(SensorValue(pot) > 1500){
				motor[leftlift] = -127;
				motor[rightlift] = -127;
			}
			else
			{
				motor[leftlift] = 10;
				motor[rightlift] = 10;
			}
		}
	wait1Msec(700);
	    motor[leftlift]=10;
	    motor[rightlift]=10;
	    motor[leftintake]=0;
	    motor[rightintake]=0;
	wait1Msec(50);
	    motor[leftfrontdrive]=127;
	    motor[leftmiddledrive]=127;
	    motor[rightfrontdrive]=127;
	    motor[leftreardrive]=127;
	    motor[rightmiddledrive]=127;
	    motor[rightreardrive]=127;
	wait1Msec(1200);
	    motor[leftfrontdrive]=0;
	    motor[rightmiddledrive]=0;
	    motor[rightfrontdrive]=0;
	    motor[leftmiddledrive]=0;
	    motor[leftreardrive]=0;
	    motor[rightreardrive]=0;
	wait1Msec(500);
     	motor[leftfrontdrive]=-127;
     	motor[leftmiddledrive]=-127;
	    motor[rightfrontdrive]=-127;
	    motor[leftreardrive]=-127;
	    motor[rightmiddledrive]=-127;
	    motor[rightreardrive]=-127;
	wait1Msec(1100);
	    motor[leftfrontdrive]=0;
	    motor[rightfrontdrive]=0;
	    motor[leftmiddledrive]=0;
	    motor[rightmiddledrive]=0;
	    motor[leftreardrive]=0;
	    motor[rightreardrive]=0;
	wait1Msec(2500);
        motor[leftfrontdrive]=127;
	    motor[rightfrontdrive]=127;
	    motor[leftmiddledrive]=127;
	    motor[rightmiddledrive]=127;
	    motor[leftreardrive]=127;
	    motor[rightreardrive]=127;
	    wait1Msec(1000);
	    motor[leftfrontdrive]=0;
	    motor[rightfrontdrive]=0;
	    motor[leftmiddledrive]=0;
	    motor[rightmiddledrive]=0;
	    motor[leftreardrive]=0;
	    motor[rightreardrive]=0;
      motor[rightintake]=127;
      motor[leftintake]=127;
  wait1Msec(15000);
		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Blue Middle");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(250);						// Robot waits for 250 milliseconds

	motor[leftintake]=-127;
	motor[rightintake]=-127;
	wait1Msec(100);
	motor[leftintake]=127;
	motor[rightintake]=127;
	wait1Msec(100);
	motor[leftintake]=-127;
	motor[rightintake]=-127;
	wait1Msec(100);
	motor[leftlift]=10;
	motor[rightlift]=10;
  motor[leftfrontdrive]=127;
	motor[rightfrontdrive]=127;
	motor[leftmiddledrive]=127;
	motor[rightmiddledrive]=127;
	motor[leftreardrive]=127;
	motor[rightreardrive]=127;
	wait1Msec(2250);
	motor[rightlift]=40;
	motor[leftlift]=40;
  motor[leftfrontdrive]=-127;
	motor[rightfrontdrive]=127;
	motor[leftmiddledrive]=-127;
	motor[rightmiddledrive]=127;
	motor[leftreardrive]=-127;
	motor[rightreardrive]=127;
	wait1Msec(533);
  motor[leftfrontdrive]=127;
	motor[rightfrontdrive]=127;
	motor[leftmiddledrive]=127;
	motor[rightmiddledrive]=127;
	motor[leftreardrive]=127;
	motor[rightreardrive]=127;
	motor[rightlift]=10;
	motor[leftlift]=10;
	wait1Msec(400);
  motor[leftfrontdrive]=0;
	motor[rightfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[rightmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(200);
  motor[leftfrontdrive]=-127;
	motor[rightfrontdrive]=-127;
	motor[leftmiddledrive]=-127;
	motor[rightmiddledrive]=-127;
	motor[leftreardrive]=-127;
	motor[rightreardrive]=-127;
  wait1Msec(400);
  motor[leftfrontdrive]=127;
	motor[rightfrontdrive]=-127;
	motor[leftmiddledrive]=127;
	motor[rightmiddledrive]=-127;
	motor[leftreardrive]=127;
	motor[rightreardrive]=-127;
	wait1Msec(550);
  motor[leftfrontdrive]=-127;
	motor[rightfrontdrive]=-127;
	motor[leftmiddledrive]=-127;
	motor[rightmiddledrive]=-127;
	motor[leftreardrive]=-127;
	motor[rightreardrive]=-127;
  motor[rightlift]=-10;
  motor[leftlift]=-10;
	wait1Msec(2050);
  motor[leftfrontdrive]=0;
	motor[rightfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[rightmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(2000);
  if(SensorValue(pot) <1400)
  {
			if(SensorValue(pot) < 1250){
				motor[leftlift] = 127;
				motor[rightlift] = 127;
			}
			else if(SensorValue(pot) > 1500){
				motor[leftlift] = -127;
				motor[rightlift] = -127;
			}
			else
			{
				motor[leftlift] = 10;
				motor[rightlift] = 10;
			}
		}
	wait1Msec(700);
	motor[leftlift]=10;
	motor[rightlift]=10;
	motor[leftintake]=0;
	motor[rightintake]=0;
	wait1Msec(50);
	motor[leftfrontdrive]=127;
	motor[leftmiddledrive]=127;
	motor[rightfrontdrive]=127;
	motor[leftreardrive]=127;
	motor[rightmiddledrive]=127;
	motor[rightreardrive]=127;
	wait1Msec(1200);
	motor[leftfrontdrive]=0;
	motor[rightmiddledrive]=0;
	motor[rightfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(500);
 	motor[leftfrontdrive]=-127;
 	motor[leftmiddledrive]=-127;
	motor[rightfrontdrive]=-127;
	motor[leftreardrive]=-127;
	motor[rightmiddledrive]=-127;
	motor[rightreardrive]=-127;
	wait1Msec(1100);
	motor[leftfrontdrive]=0;
	motor[rightfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[rightmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(2500);
  motor[leftfrontdrive]=127;
	motor[rightfrontdrive]=127;
	motor[leftmiddledrive]=127;
	motor[rightmiddledrive]=127;
	motor[leftreardrive]=127;
	motor[rightreardrive]=127;
	wait1Msec(1000);
	motor[leftfrontdrive]=0;
	motor[rightfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[rightmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightreardrive]=0;
  motor[rightintake]=127;
  motor[leftintake]=127;
  wait1Msec(15000);

		break;
	case 2:
		//If count = 2, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "red hang");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(250);						// Robot waits for 250 milliseconds

	motor[leftintake]=-127;
	motor[rightintake]=-127;
	wait1Msec(100);
	motor[leftintake]=0;
	motor[rightintake]=0;
	wait1Msec(300);
	motor[leftintake]=-127;
	motor[rightintake]=-127;
	wait1Msec(100);
	motor[rightlift]=127;
	motor[leftlift]=127;
	wait1Msec(150);
	motor[rightlift]=10;
	motor[leftlift]=10;
	wait1Msec(50);
	motor[leftfrontdrive]=80;
	motor[leftmiddledrive]=80;
	motor[leftreardrive]=80;
	motor[rightmiddledrive]=80;
	motor[rightfrontdrive]=80;
	motor[rightreardrive]=80;
	wait1Msec(800);
	motor[leftfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightmiddledrive]=0;
	motor[rightfrontdrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(500);
	motor[leftfrontdrive]=-127;
	motor[leftmiddledrive]=-127;
	motor[leftreardrive]=-127;
	motor[rightmiddledrive]=-127;
	motor[rightfrontdrive]=-127;
	motor[rightreardrive]=-127;
	wait1Msec(550);
	motor[leftfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightmiddledrive]=0;
	motor[rightfrontdrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(2500);
	nMotorEncoder(leftreardrive) = 0;
	nMotorEncoder(rightreardrive) = 0;
	motor[rightlift]=10;
	motor[leftlift]=10;
	wait1Msec(10);
	motor[rightreardrive] = 80;
	motor[rightmiddledrive]	= 80;
	motor[leftmiddledrive] = 80;
	motor[leftfrontdrive]	= 80;
	motor[rightfrontdrive] = 80;
	motor[leftreardrive]	= 80;
	wait1Msec(850);
	motor[rightreardrive] = 0;
	motor[rightmiddledrive]	= 0;
	motor[rightfrontdrive] = 0;
	motor[leftfrontdrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftreardrive]	= 0;
	motor[leftlift]=50;
  motor[rightlift]=50;
	wait1Msec(750);
	motor[leftlift] = 10;
	motor[rightlift] = 10;
  motor[leftfrontdrive]=-127;
	motor[rightfrontdrive]=127;
	motor[leftmiddledrive]=-127;
	motor[rightmiddledrive]=127;
	motor[leftreardrive]=-127;
	motor[rightreardrive]=127;
	wait1Msec(500);
	motor[leftreardrive] = 0;
	motor[leftmiddledrive] = 0;
	motor[leftfrontdrive] = 0;
	motor[rightreardrive] = 0;
	motor[rightmiddledrive] = 0;
	motor[rightfrontdrive] = 0;
	wait1Msec(50);
	motor[rightreardrive] = 127;
	motor[rightmiddledrive]	= 127;
	motor[leftmiddledrive] = 127;
	motor[leftfrontdrive]	= 127;
	motor[leftmiddledrive] = 127;
	motor[leftreardrive]	= 127;
	wait1Msec(1000);
	motor[rightreardrive] = 0;
	motor[rightmiddledrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftfrontdrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftreardrive]	= 0;
	wait1Msec(50);
	motor[leftlift] = 127;
	motor[rightlift] = 127;
	wait1Msec(500);
	motor[leftlift] = 10;
	motor[rightlift] = 10;
	motor[rightreardrive] = 80;
	motor[rightmiddledrive]	= 80;
	motor[leftmiddledrive] = 80;
	motor[leftfrontdrive]	= 80;
	motor[leftmiddledrive] = 80;
	motor[leftreardrive]	= 80;
	wait1Msec(1500);
	motor[rightreardrive] = 0;
	motor[rightmiddledrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftfrontdrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftreardrive]	= 0;
	motor[leftlift] = 0;
	motor[rightlift] = 0;
	motor[leftintake]=127;
	motor[rightintake]=127;
	wait1Msec(15000);
// Insert "Blue Left" autonomous code here.


		break;

	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Blue hang");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(250);						// Robot waits for 250 milliseconds

	motor[leftintake]=-127;
	motor[rightintake]=-127;
	wait1Msec(100);
	motor[leftintake]=0;
	motor[rightintake]=0;
	wait1Msec(300);
	motor[leftintake]=-127;
	motor[rightintake]=-127;
	wait1Msec(100);
	motor[rightlift]=127;
	motor[leftlift]=127;
	wait1Msec(150);
	motor[rightlift]=10;
	motor[leftlift]=10;
	wait1Msec(50);
	motor[leftfrontdrive]=80;
	motor[leftmiddledrive]=80;
	motor[leftreardrive]=80;
	motor[rightmiddledrive]=80;
	motor[rightfrontdrive]=80;
	motor[rightreardrive]=80;
	wait1Msec(800);
	motor[leftfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightmiddledrive]=0;
	motor[rightfrontdrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(500);
	motor[leftfrontdrive]=-127;
	motor[leftmiddledrive]=-127;
	motor[leftreardrive]=-127;
	motor[rightmiddledrive]=-127;
	motor[rightfrontdrive]=-127;
	motor[rightreardrive]=-127;
	wait1Msec(550);
	motor[leftfrontdrive]=0;
	motor[leftmiddledrive]=0;
	motor[leftreardrive]=0;
	motor[rightmiddledrive]=0;
	motor[rightfrontdrive]=0;
	motor[rightreardrive]=0;
	wait1Msec(2500);
	nMotorEncoder(leftreardrive) = 0;
	nMotorEncoder(rightreardrive) = 0;
	motor[rightlift]=0;
	motor[leftlift]=0;
	wait1Msec(10);
	motor[rightreardrive] = 127;
	motor[rightmiddledrive]	= 127;
	motor[leftmiddledrive] = 127;
	motor[leftfrontdrive]	= 127;
	motor[rightfrontdrive] = 127;
	motor[leftreardrive]	= 127;
	wait1Msec(850);
	motor[rightreardrive] = 0;
	motor[rightmiddledrive]	= 0;
	motor[rightfrontdrive] = 0;
	motor[leftfrontdrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftreardrive]	= 0;
	motor[leftlift]=50;
  motor[rightlift]=50;
	wait1Msec(750);
	motor[leftlift] = 10;
	motor[rightlift] = 10;
  motor[leftfrontdrive]=127;
	motor[rightfrontdrive]=-127;
	motor[leftmiddledrive]=127;
	motor[rightmiddledrive]=-127;
	motor[leftreardrive]=127;
	motor[rightreardrive]=-127;
	wait1Msec(500);
	motor[leftreardrive] = 0;
	motor[leftmiddledrive] = 0;
	motor[leftfrontdrive] = 0;
	motor[rightreardrive] = 0;
	motor[rightmiddledrive] = 0;
	motor[rightfrontdrive] = 0;
	wait1Msec(50);
	motor[rightreardrive] = 127;
	motor[rightmiddledrive]	= 127;
	motor[leftmiddledrive] = 127;
	motor[leftfrontdrive]	= 127;
	motor[leftmiddledrive] = 127;
	motor[leftreardrive]	= 127;
	wait1Msec(1000);
	motor[rightreardrive] = 0;
	motor[rightmiddledrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftfrontdrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftreardrive]	= 0;
	wait1Msec(50);
	motor[leftlift] = 127;
	motor[rightlift] = 127;
	wait1Msec(500);
	motor[leftlift] = 10;
	motor[rightlift] = 10;
	motor[rightreardrive] = 80;
	motor[rightmiddledrive]	= 80;
	motor[leftmiddledrive] = 80;
	motor[leftfrontdrive]	= 80;
	motor[leftmiddledrive] = 80;
	motor[leftreardrive]	= 80;
	wait1Msec(1500);
	motor[rightreardrive] = 0;
	motor[rightmiddledrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftfrontdrive]	= 0;
	motor[leftmiddledrive] = 0;
	motor[leftreardrive]	= 0;
	motor[leftlift] = 0;
	motor[rightlift] = 0;
	motor[leftintake]=127;
	motor[rightintake]=127;
	wait1Msec(15000);
		// Insert "Blue Right" autonomous code here.

		break;
	default:
		displayLCDCenteredString(0, "No choice");
		displayLCDCenteredString(1, "was made! )=<");
		break;
	}}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		motor[rightfrontdrive]=vexRT[Ch2];
		motor[rightmiddledrive]=vexRT[Ch2];
		motor[rightreardrive]=vexRT[Ch2];
		motor[leftfrontdrive]=vexRT[Ch3];
		motor[leftmiddledrive]=vexRT[Ch3];
		motor[leftreardrive]=vexRT[Ch3];
		if (1 == 1)
		{
		clearLCDLine(0);											// Clear line 1 (0) of the LCD
		clearLCDLine(1);											// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);
    displayLCDPos(1,0);
    displayNextLCDNumber(SensorValue(pot));

		//Short delay for the LCD refresh rate
		wait1Msec(100);
		}
		if(vexRT[Btn5U]==1)
		{
			if(SensorValue(pot) < 1700){
				motor[leftlift] = 127;
				motor[rightlift] = 127;
			}
			else if(SensorValue(pot) > 1700){
				motor[leftlift] = 70;
				motor[rightlift] = 70;
			}
		}
		else if(vexRT[Btn5D]==1)
		{
			if(SensorValue(pot) < 1700){
				motor[leftlift] = -127;
				motor[rightlift] = -127;
			}
			else if(SensorValue(pot) > 1700){
				motor[leftlift] = -70;
				motor[rightlift] = -70;
			}
		}
		else
		{
			motor[leftlift] = 10;
			motor[rightlift] = 10;
		}
		if (vexRT[Btn6U]==1)
		{
			motor[leftintake]=-127;
			motor[rightintake]=-127;
		}
		else if (vexRT[Btn6D]==1)
		{
			motor[leftintake]=127;
			motor[rightintake]=127;
		}
		else
		{
			motor[leftintake]=0;
			motor[rightintake]=0;
		}
		if (vexRT[Btn7U]==1)
		{
			SensorValue[cat1]=0;
			SensorValue[cat2]=0;
		}
		else if (vexRT[Btn7D]==1)
		{
			SensorValue[cat2]=1;
			SensorValue[cat1]=1;
		}
		if (vexRT[Btn8U]==1)
		{
			SensorValue[hang2]=1;
			SensorValue[hang1]=1;
		}
		else if (vexRT[Btn8D]==1)
		{
			SensorValue[hang1]=0;
			SensorValue[hang2]=0;
		}
		while(vexRT[Btn7L]==1)
		{
			if(SensorValue(pot) < 1450){
				motor[leftlift] = 127;
				motor[rightlift] = 127;
			}
			else if(SensorValue(pot) > 1500){
				motor[leftlift] = -127;
				motor[rightlift] = -127;
			}
			else
			{
				motor[leftlift] = 10;
				motor[rightlift] = 10;
			}
		}
		if(vexRT[Btn7R]==1)
		{
			if(SensorValue(pot) < 1900){
				motor[leftlift] = 127;
				motor[rightlift] = 127;
			}
			else if(SensorValue(pot) > 2025){
				motor[leftlift] = -127;
				motor[rightlift] = -127;
			}
			else
			{
				motor[leftlift] = 10;
				motor[rightlift] = 10;
			}
		}
		if(vexRT[Btn8L]==1)
		{
			if(SensorValue(pot) < 700){
				motor[leftlift] = 50;
				motor[rightlift] = 50;
			}
			else if(SensorValue(pot) > 710){
				motor[leftlift] = -50;
				motor[rightlift] = -50;
			}
			else if(SensorValue(pot) < 703){
				motor[leftlift] = 35;
				motor[rightlift] = 35;
			}
			else if(SensorValue(pot) > 707){
				motor[leftlift] = -35;
				motor[rightlift] = -35;
			}
			else
			{
				motor[leftlift] = 10;
				motor[rightlift] = 10;
			}
		}
	}
}